### ISSUE TITLE
ImportError: cannot import name packet

### ISSUE THREAD

**Issue by cleesmith** [jasonish/py-idstools#18]
I'm probably missing something simple, but this was working before ... but now:
```
>>> import idstools
>>> from idstools import packet
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name packet
```
with:
python 2.7.6
pip freeze ```idstools==0.4.4``` ... this worked using ```0.5.0dev```

Please ignore the above, I forgot that you have to do:
```pip install git+https://github.com/jasonish/py-idstools.git```
and not:
```pip install idstools```
... but maybe this will help others that make the same mistake.
